---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Build Docker image for NGINX
      community.docker.docker_image:
        name: "{{ ECR_REPOSITORY_URL }}:{{ IMAGE_VERSION }}"
        source: build
        build:
          path: "../files"
          nocache: true
          rm: true
        state: present

    - name: Get ECR token
      shell: "aws ecr get-login-password --region {{ REGION }}"
      register: ecr_token

    - name: Login to AWS ECR
      community.docker.docker_login:
        username: AWS
        password: "{{ lookup('pipe', 'aws ecr get-login-password --region ' + REGION) }}"
        registry_url: "{{ ECR_REPOSITORY_URL }}"

    - name: Tag Docker image
      community.docker.docker_image:
        name: "{{ ECR_REPOSITORY_URL }}:{{ IMAGE_VERSION }}"
        repository: "{{ ECR_REPOSITORY_URL }}:{{ IMAGE_VERSION }}"
        push: no
        source: local

    - name: Push Docker image to ECR
      community.docker.docker_image:
        name: "{{ ECR_REPOSITORY_URL }}:{{ IMAGE_VERSION }}"
        push: yes
        source: local
