---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:

    - name: Remove existing Docker builder
      ansible.builtin.command:
        cmd: docker buildx rm phrase_builder
      ignore_errors: yes

    - name: Create a new Docker builder which supports buildx
      ansible.builtin.command:
        cmd: docker buildx create --name phrase_builder --use
      register: buildx_create

    - name: Start up the builder instance
      ansible.builtin.command:
        cmd: docker buildx inspect --bootstrap

    - name: Build and push Docker image
      ansible.builtin.shell:
        cmd: >-
          aws ecr get-login-password --region "{{ REGION }}" | docker login --username AWS --password-stdin "{{ ECR_REPOSITORY_URL }}" &&
          docker buildx build
          --platform linux/amd64
          -t "{{ ECR_REPOSITORY_URL }}:{{ IMAGE_VERSION }}"
          --push
          --no-cache
          ../files
      register: docker_build
